apiVersion: 1

datasources:
  - name: PostgreSQL-Monitoring
    type: postgres
    access: proxy
    url: postgres:5432
    database: jobinsight
    user: jobinsight
    secureJsonData:
      password: jobinsight
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1300
      timescaledb: false
    isDefault: true
    editable: true
